name: Delete Files
on:
  workflow_dispatch:
    inputs:
      dataset_id:
        description: 'OpenNeuro Accession Number'
        default: ds000000
        required: true
      file_ext:
        description: 'File Extensions'
        default: '_dwi.gqi.fib.gz'
        required: true        
jobs:
  src_quality_check:
    name: Delete Release File
    runs-on: ubuntu-20.04
    steps:     
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get Subject List
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          files=($(aws s3 ls --no-sign-request --region eu-west-1 s3://openneuro.org/${{ inputs.dataset_id }} --recursive | grep '/dwi/' | grep 'nii.gz' | awk '{print $NF}' | awk -F'/dwi/' '{print $1}' | awk -F'/sub-' '/sub-/ {print "sub-" $2}' | sort -u | tr '/' '_' | tr '\n' ' '))
          for file in "${files[@]}"; do
            echo "Processing $file"
            gh release delete-asset ${{ inputs.dataset_id }} ${file}${{ inputs.file_ext }}
          done
        
