name: DSI Studio Cloud
on: 
  workflow_dispatch:
    inputs:
      id:
        description: 'OpenNeuro Accession Number'
        default: ds001743
        required: true
      src_param:
        required: false
        default: ""
        description: 'Other Reconstruction Parameters'
      
jobs:    
  open_neuro:
    name: Download OpenNeuro
    runs-on: ubuntu-20.04
    outputs:
      subjects: ${{ steps.data.outputs.subjects }}
      files: ${{ steps.data.outputs.files }}
      dataset_description: ${{ steps.data.outputs.dataset_description }}
    steps:
      - name: OpenNeuro
        id: data
        run: |
          # Process dataset_description.json
          aws s3 sync --no-sign-request --region eu-west-1 --exclude "*" --include "dataset_description.json" s3://openneuro.org/${{ github.event.inputs.id }} .
          content=`cat dataset_description.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=dataset_description::$content"  

          # Get subjects
          SUBJECTS=$(aws s3 ls --no-sign-request --region eu-west-1 s3://openneuro.org/ds001743 --recursive | grep 'dwi' | awk '{print $NF}' | awk -F'/dwi/' '{print $1}' | awk -F'/sub-' '/sub-/ {print "sub-" $2}' | jq -R -s -c 'split("\n")[:-1]')
          FILES=$(echo "$SUBJECTS" | tr '/' '_')
          echo "::set-output name=subjects::$SUBJECTS"
          echo "::set-output name=files::$FILES"
          
  download_data:
    name: NIFTI to SRC
    needs: open_neuro
    runs-on: ubuntu-20.04
    outputs:
      subjects: ${{ needs.open_neuro.outputs.subjects }}
      files: ${{ needs.open_neuro.outputs.files }}
      dataset_description: ${{ needs.open_neuro.outputs.dataset_description }}
    strategy:
      matrix:
        subjects: ${{ fromjson(needs.open_neuro.outputs.subjects) }}
    steps:
      - name: Check Files
        id: check_link
        run: |
          FILE = $(echo ${{ matrix.subjects }} | tr '/' '_')
          echo "FILE=$FILE" >> $GITHUB_ENV
          if curl --head --silent --fail https://github.com/frankyeh/DSI-Studio-Cloud/releases/download/${{ github.event.inputs.id }}/$FILE.raw.src.gz; then
            echo "src_exists=true" >> $GITHUB_ENV
          else
            echo "src_exists=false" >> $GITHUB_ENV
          fi
      - name: Download OpenNeuro
        if: env.src_exists == 'false' 
        run: |
          aws s3 sync --no-sign-request --region eu-west-1 --exclude "*" --include "*dwi.*" s3://openneuro.org/${{ github.event.inputs.id }}/${{ matrix.subjects }} ${{ github.event.inputs.id }}
          curl -sL "https://github.com/frankyeh/DSI-Studio/releases/download/2024.06.12/dsi_studio_ubuntu2004.zip" | jar x && chmod 777 ./dsi-studio/dsi_studio
          ./dsi-studio/dsi_studio --action=src --source=./${{ github.event.inputs.id }}/dwi
          mv ./${{ github.event.inputs.id }}/dwi/*.src.gz ./${FILE}.raw.src.gz
      - name: Create Release
        if: env.src_exists == 'false' 
        uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: true
          artifacts: ./${FILE}.raw.src.gz
          name: "${{ fromjson(needs.open_neuro.outputs.dataset_description).Name }}"
          tag: ${{ github.event.inputs.id }}     

  topup_eddy:
    name: TOPUP/EDDY
    needs: download_data
    outputs:
      files: ${{ needs.download_data.outputs.files }}
      dataset_description: ${{ needs.download_data.outputs.dataset_description }}    
    strategy:
      matrix:
        files: ${{ fromjson(needs.download_data.outputs.files) }}
    runs-on: ubuntu-20.04
    steps:
      - name: Check Files
        id: check_link
        run: |
          if curl --head --silent --fail https://github.com/frankyeh/DSI-Studio-Cloud/releases/download/${{ github.event.inputs.id }}/${{ matrix.files }}.src.gz; then
            echo "file_exists=true" >> $GITHUB_ENV
          else
            echo "file_exists=false" >> $GITHUB_ENV
          fi
      - name: Cache FSL environment
        if: env.file_exists == 'false'
        id: cache-fsl
        uses: actions/cache@v3
        with:
          path: /opt/fsl
          key: ${{ runner.os }}-fsl
      - name: Prepare FSL environment
        if: steps.cache-fsl.outputs.cache-hit != 'true' && env.file_exists == 'false'
        run: curl -sSL https://fsl.fmrib.ox.ac.uk/fsldownloads/fsl-6.0.4-centos7_64.tar.gz | tar zxv --no-same-owner -C /opt --exclude='fsl/doc' --exclude='fsl/refdoc' --exclude='fsl/python/oxford_asl' --exclude='fsl/data/possum' --exclude='fsl/data/first' --exclude='fsl/data/mist' --exclude='fsl/data/atlases' --exclude='fsl/data/xtract_data' --exclude='fsl/extras/doc' --exclude='fsl/extras/man' --exclude='fsl/extras/src' --exclude='fsl/src'
      - name: Eddy
        if: env.file_exists == 'false'
        run: |
          export OS="Linux"
          export FSLDIR="/opt/fsl"
          export FSL_DIR="$FSLDIR"
          export FSLOUTPUTTYPE="NIFTI_GZ"
          export FSLMULTIFILEQUIT="TRUE"
          export LD_LIBRARY_PATH="$FSLDIR/lib:$LD_LIBRARY_PATH"
          export FSLTCLSH="/usr/bin/tclsh"
          export FSLWISH="/usr/bin/wish"
          export PATH="$FSLDIR/bin:$PATH"
          curl -sSLO "https://github.com/frankyeh/DSI-Studio/releases/download/2024.06.12/dsi_studio_ubuntu2004.zip" && unzip -q *.zip
          wget https://github.com/frankyeh/DSI-Studio-Cloud/releases/download/${{ github.event.inputs.id }}/${{ matrix.files }}.raw.src.gz
          ./dsi-studio/dsi_studio --action=rec --source=${{ matrix.files }}.raw.src.gz --cmd="[Step T2][Corrections][EDDY]" --save_src=${{ matrix.files }}.src.gz ${{ github.event.inputs.src_param}}               
      - name: Create Release
        if: env.file_exists == 'false'
        uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: true
          artifacts: ${{ matrix.files }}.src.gz
          name: "${{ fromjson(needs.download_data.outputs.dataset_description).Name }}"
          tag: ${{ github.event.inputs.id }}  
          
  src_quality_check:
    name: SRC Quality Check
    needs: topup_eddy
    outputs:
      files: ${{ fromjson(needs.topup_eddy.outputs.files) }}
      dataset_description: ${{ needs.topup_eddy.outputs.dataset_description }}    
    runs-on: ubuntu-20.04
    steps:                
      - name: Quality Check
        run: |        
          curl -sSLO "https://github.com/frankyeh/DSI-Studio/releases/download/2024.06.12/dsi_studio_ubuntu2004.zip" && unzip -q *.zip
          ./dsi-studio/dsi_studio --action=qc --source=./${{ github.event.inputs.id }}-corrected_src
          mv qc.txt corrected_qc.txt             
      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: true
          artifacts: corrected_qc.txt 
          name: "${{ fromjson(needs.topup_eddy.outputs.dataset_description).Name }}"
          tag: ${{ github.event.inputs.id }}          

  reconstruction:
    name: SRC to FIB
    continue-on-error: true
    needs: topup_eddy
    outputs:
      files: ${{ needs.topup_eddy.outputs.files }}
      dataset_description: ${{ needs.topup_eddy.outputs.dataset_description }}    
    strategy:
      matrix:
        files: ${{ fromjson(needs.topup_eddy.outputs.files) }}
    runs-on: ubuntu-20.04
    steps:
      - name: Check If Done
        run: |
          wget https://github.com/frankyeh/DSI-Studio-Cloud/releases/download/${{ github.event.inputs.id }}/${{ matrix.files }}.gqi.fib.gz || true
          wget https://github.com/frankyeh/DSI-Studio-Cloud/releases/download/${{ github.event.inputs.id }}/${{ matrix.files }}.qsdr.fib.gz || true
          if [ ! -f "${{ matrix.files }}.qsdr.fib.gz" ]; then
            echo "file_exists=false" >> $GITHUB_ENV
          else
            echo "file_exists=true" >> $GITHUB_ENV
          fi
      - name: GQI and QSDR Reconstruction
        if: env.file_exists == 'false'
        run: |
          wget https://github.com/frankyeh/DSI-Studio-Cloud/releases/download/${{ github.event.inputs.id }}/${{ matrix.files }}
          curl -sSLO "https://github.com/frankyeh/DSI-Studio/releases/download/2024.06.12/dsi_studio_ubuntu2004.zip" && unzip -q *.zip
          ./dsi-studio/dsi_studio --action=rec --source=${{ matrix.files }} --output=${{ matrix.files }}.gqi.fib.gz ${{ github.event.inputs.src_param}}  
          ./dsi-studio/dsi_studio --action=rec --source=${{ matrix.files }} --output=${{ matrix.files }}.qsdr.fib.gz --method=7  ${{ github.event.inputs.src_param}}
      - name: Create Release
        if: env.file_exists == 'false'
        uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: true
          artifacts: |
            ${{ matrix.files }}.gqi.fib.gz
            ${{ matrix.files }}.qsdr.fib.gz
          name: "${{ fromjson(needs.topup_eddy.outputs.dataset_description).Name }}"
          tag: ${{ github.event.inputs.id }}  
      - name: Save GQI FIB Files
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ github.event.inputs.id }}_GQI_fib
          path: ./${{ matrix.files }}.gqi.fib.gz              
      - name: Save QSDR FIB Files
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ github.event.inputs.id }}_QSDR_fib
          path: ./${{ matrix.files }}.qsdr.fib.gz          
          
  database_construction:
    name: Create Database
    needs: reconstruction
    outputs:
      files: ${{ needs.reconstruction.outputs.files }}
      dataset_description: ${{ needs.reconstruction.outputs.dataset_description }}    
    runs-on: ubuntu-20.04
    steps:
      - name: Check If Done
        run: |
          wget https://github.com/frankyeh/DSI-Studio-Cloud/releases/download/${{ github.event.inputs.id }}/${{ github.event.inputs.id }}.db.fib.gz || true
          if [ ! -f "${{ github.event.inputs.id }}.db.fib.gz" ]; then
            echo "file_exists=false" >> $GITHUB_ENV
          else
            echo "file_exists=true" >> $GITHUB_ENV
          fi
      - name: Prepare FIB Files
        if: env.file_exists == 'false'
        uses: actions/download-artifact@v3.0.0
        with:
          name: ${{ github.event.inputs.id }}_QSDR_fib
      - name: Database Construction
        if: env.file_exists == 'false'
        run: |        
          aws s3 sync --no-sign-request --region eu-west-1 --exclude "*" --include "participants.tsv" s3://openneuro.org/${{ github.event.inputs.id }} .
          curl -sSLO "https://github.com/frankyeh/DSI-Studio/releases/download/2024.06.12/dsi_studio_ubuntu2004.zip" && unzip -q *.zip
          if [ -f participants.tsv ]; then
            ./dsi-studio/dsi_studio --action=atl --source=*.fib.gz --cmd=db --demo=participants.tsv --output=${{ github.event.inputs.id }}.db.fib.gz
          else
            ./dsi-studio/dsi_studio --action=atl --source=*.fib.gz --cmd=db --output=${{ github.event.inputs.id }}.db.fib.gz
          fi
      - name: Create Release
        if: env.file_exists == 'false'
        uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: true
          artifacts: ${{ github.event.inputs.id }}.db.fib.gz
          name: "${{ fromjson(needs.reconstruction.outputs.dataset_description).Name }}"
          tag: ${{ github.event.inputs.id }}          
     
