name: DSI Studio Data Hub
on: 
  workflow_dispatch:
    inputs:
      dataset_id:
        description: 'OpenNeuro Accession Number'
        default: ds001378
        required: true
      
jobs:    
  info:
    uses: ./.github/workflows/add_info.yml
    name: Access OpenNeuro
    with:
      dataset_id: ${{ inputs.dataset_id }}    
  nii2src:
    uses: ./.github/workflows/nii2src.yml
    needs: info
    name: Call NII to SRC
    with:
      dataset_id: ${{ inputs.dataset_id }}      
          
  src_quality_check:
    uses: ./.github/workflows/src_qc.yml
    needs: nii2src
    name: SRC Quality Check
    with:
      src_list: 'src.gz'
      dataset_id: ${{ inputs.dataset_id }} 

  reconstruction:
    uses: ./.github/workflows/recon.yml
    needs: nii2src
    name: SRC to FIB
    with:
      dataset_id: ${{ inputs.dataset_id }}
          
  database_construction:
    uses: ./.github/workflows/create_db.yml
    needs: reconstruction
    strategy:
      matrix:
          metrics: ['qa','dti_fa']
    name: Create Database
    with:
      metrics: ${{ matrix.metrics}}
      dataset_id: ${{ inputs.dataset_id }}
