name: STEP T1 NII to SRC

on:
  workflow_dispatch:
    inputs:
      dataset_id:
        description: 'OpenNeuro Accession Number'
        default: ds001378
        required: true
  workflow_call:
    inputs:
      dataset_id:
        description: 'OpenNeuro Accession Number'
        default: ds001378
        required: true
        type: string

jobs:
  nii2src:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        batch: [1, 2, 3, 4, 5, 6, 7, 8]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get Subject List
        id: data
        run: |
          SUBJECTS=$(aws s3 ls --no-sign-request --region eu-west-1 s3://openneuro.org/${{ inputs.dataset_id }} --recursive | grep '/dwi/' | grep 'nii.gz' | awk '{print $NF}' | awk -F'/dwi/' '{print $1}' | awk -F'/sub-' '/sub-/ {print "sub-" $2}' | sort -u | tr '\n' ' ')
          echo "subjects=$SUBJECTS" >> $GITHUB_OUTPUT
      - name: Download and Extract DSI Studio
        run: |
          curl -sL "https://github.com/frankyeh/DSI-Studio/releases/download/2024.06.12/dsi_studio_ubuntu2004.zip" | jar x && chmod 777 ./dsi-studio/dsi_studio
      - name: Process Subjects
        run: |
          subjects=($(echo "${{ steps.data.outputs.subjects }}"))
          start=$(( ( ${{ matrix.batch }} - 1 ) * $(( (${#subjects[@]} + 7) / 8 )) ))
          end=$(( $start + batch_size - 1 ))
          for (( i=$start; i<=$end && i< ${#subjects[@]}; i++ )); do
            subject=${subjects[i]}
            file=$(echo $subject | tr '/' '_')
            echo "Processing $file"
            if curl --head --silent --fail https://github.com/frankyeh/DSI-Studio-Cloud/releases/download/${{ inputs.dataset_id }}/${file}_dwi.raw.src.gz; then
              echo "$file exists."
            else
              echo "Downloading and processing $subject"
              aws s3 sync --no-sign-request --region eu-west-1 --exclude "*" --include "*dwi.*" s3://openneuro.org/${{ inputs.dataset_id }}/$subject $subject
              ./dsi-studio/dsi_studio --action=src --source=./$subject/dwi
              mv ./$subject/dwi/*.src.gz ./${file}_dwi.raw.src.gz
            fi
          done
      - name: Upload Results
        if: ${{ always() }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
        run: |
          if ls ./*.src.gz 1> /dev/null 2>&1; then
            gh release upload "${{ inputs.dataset_id }}" ./*.src.gz
          else
            echo "No .src.gz files to upload."
          fi
