name: STEP T2 Reconstruction

on:
  workflow_dispatch:
    inputs:
      dataset_id:
        description: 'OpenNeuro Accession Number'
        default: ds001378
        required: true
  workflow_call:
    inputs:
      dataset_id:
        description: 'OpenNeuro Accession Number'
        default: ds001378
        required: true
        type: string

jobs:
  reconstruction:
    name: SRC to FIB
    strategy:
      fail-fast: false
      matrix:
        batch: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: GQI and QSDR Reconstruction
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -sL "https://github.com/frankyeh/DSI-Studio/releases/download/2024.06.12/dsi_studio_ubuntu2004.zip" | jar x && chmod 777 ./dsi-studio/dsi_studio  
          subjects=($(aws s3 ls --no-sign-request --region eu-west-1 s3://openneuro.org/${{ inputs.dataset_id }} --recursive | grep '/dwi/' | grep 'nii.gz' | awk '{print $NF}' | awk -F'/dwi/' '{print $1}' | awk -F'/sub-' '/sub-/ {print "sub-" $2}' | sort -u ))
          for (( i=${{ matrix.batch }}; i< ${#subjects[@]}; i+=16 )); do        
            subject=${subjects[i]}
            file=$(echo $subject | tr '/' '_')
            if curl --head --silent --fail https://github.com/frankyeh/DSI-Studio-Cloud/releases/download/${{ inputs.dataset_id }}/${file}_dwi.qsdr.fib.gz; then
              echo "${file}_dwi.qsdr.fib.gz exists, skip"
            else
              url="https://github.com/frankyeh/DSI-Studio-Cloud/releases/download/${{ inputs.dataset_id }}/${file}_dwi.src.gz"
              echo "download ${url} for reconstruction"
              if curl --head --silent --fail $url; then
                wget -q $url
                ./dsi-studio/dsi_studio --action=rec --source=${file}_dwi.src.gz --output=${file}_dwi.gqi.fib.gz
                ./dsi-studio/dsi_studio --action=rec --source=${file}_dwi.src.gz --output=${file}_dwi.qsdr.fib.gz --method=7
                gh release upload "${{ inputs.dataset_id }}" *.fib.gz  
                rm *.src.gz
                rm *.fib.gz
              else
                echo "ERROR: cannot find SRC file $url for reconstruction" >&2
                exit 1
              fi
            fi
          done
 
